[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault = "3TyFQro3GCCfd4yV5Wmbb2Rrzh35TreXJWMfbFs5dz5S"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
