[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
ulysses-protocol = "7s1UK1nQWK7CrNcaS576gbpMjMqrph1vArRepnQYLki7"
vault = "5ahewo5SgzMyWN2byK5PraBZm85ayuvM8KxAEFoFwh9y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
